import React, { useEffect } from 'react';
import './Legal.css';
import updateMetaTags from '../utils/updateMetaTags';

const Disclaimer = () => {
  useEffect(() => {
    updateMetaTags({
      title: 'Disclaimer | Partner\'s Tours & Travels',
      description: 'Travel disclaimer and information for partnertours.in users.',
    });
  }, []);
  return (
    <div className="legal-page">
      <section className="legal-hero">
        <div className="container">
          <h1>Disclaimer</h1>
          <p>Last Updated: May 02, 2026</p>
        </div>
      </section>

      <section className="legal-content section-padding">
        <div className="container">
          <div className="legal-text-wrapper">
            <h2>General Information</h2>
            <p>
              The information contained in this website (partner-tour.site) is for general information purposes only. The information is provided by <strong>Partner's Tours & Travels</strong>, and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
            </p>

            <h2>Professional Travel Advice</h2>
            <p>
              The travel information provided on this site is not a substitute for professional travel advice. Travel conditions, visa requirements, and safety protocols can change rapidly. We strongly recommend that users verify all critical information with official government sources or our travel consultants at our Chalisgaon office before making any financial commitments.
            </p>

            <h2>AdSense and Third-Party Advertising</h2>
            <p>
              This website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). Google AdSense uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. Google AdSense also uses so-called web beacons (invisible graphics). Through these web beacons, information such as visitor traffic on the pages of this offer can be evaluated. The information generated by cookies and web beacons about your use of this website (including your IP address) and delivery of advertising formats is transmitted to a Google server in the USA and stored there. This information can be passed on by Google to contracting parties of Google. However, Google will not merge your IP address with other data you have stored.
            </p>

            <h2>External Links Disclaimer</h2>
            <p>
              Through this website, you are able to link to other websites which are not under the control of Partner's Tours & Travels. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them. We are not responsible for the protection and privacy of any information which you provide whilst visiting such sites.
            </p>

            <h2>Pricing and Availability</h2>
            <p>
              All prices listed for tour packages, vehicle rentals, and flight tickets are "starting from" prices and are subject to change without notice. Prices are influenced by factors such as seasonality, hotel availability, flight fare classes, and fuel price fluctuations in the Jalgaon district and across India. <strong>Partner's Tours & Travels</strong> reserves the right to adjust prices or withdraw offers at any time based on market conditions.
            </p>

            <h2>Images and Media</h2>
            <p>
              Images used on this website are for illustrative purposes only. Actual hotels, vehicles, and destinations may vary in appearance. We use a combination of original photography and licensed stock images to represent our travel services.
            </p>

            <h2>Consent</h2>
            <p>
              By using our website, you hereby consent to our disclaimer and agree to its terms. If you do not agree with any part of this disclaimer, you must not use our website or services.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Disclaimer;
